export const GET_DATA = 'GET_DATA';
export const SET_CURRENT_STATE = 'SET_CURRENT_STATE';
export const SET_LOADING = 'SET_LOADING';
export const GET_COUNTRIES_DATA = 'GET_COUNTRIES_DATA';
export const GET_COUNTRY = 'GET_COUNTRY';
export const CURRENT_COUNTRY = 'CURRENT_COUNTRY';
